### ISSUE TITLE
Error building app in Android Studio

### ISSUE THREAD

**Issue by ahmadazarnia** [gitblit/iciql#25] opened 2016-06-01 06:25 UTC
Hi,

I have a problem when using **iciql** package with gradle (`compile 'com.gitblit.iciql:iciql:2.1.1'`)
When trying to build the project, this error occurred:

`Error:trouble processing "java/lang/AutoCloseable.class"`
`Error:Ill-advised or mistaken usage of a core class (java.* or javax.*)`
`Error:when not building a core library.`
`Error:This is often due to inadvertently including a core library file`
`Error:in your application's project, when using an IDE (such as`
`Error:Eclipse). If you are sure you're not intentionally defining a`
`Error:core class, then this is the most likely explanation of what's`
`Error:going on.`

**Comment by gitblit** [comment] 2016-06-01 12:22
This is likely caused by bundling the AutoClosable interface in the jar so that iciql can still be used by Java 6 but also enjoy try-catch-with-resources introduced in Java 7.  Is it Gradle that complains or Google's toolchain?  Is there a way to disable that verification?

**Comment by ahmadazarnia** [comment] 2016-06-05 07:32
Hi,

I'm using Android Studio and Gradle build system (I am newbie in gradle)
I've tried running app using command line with gradle and the full error report is:
```
trouble processing "java/lang/AutoCloseable.class":
Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.
This is often due to inadvertently including a core library file
in your application's project, when using an IDE (such as
Eclipse). If you are sure you're not intentionally defining a
core class, then this is the most likely explanation of what's
going on.
However, you might actually be trying to define a class in a core
namespace, the source of which you may have taken, for example,
from a non-Android virtual machine project. This will most
assuredly not work. At a minimum, it jeopardizes the
compatibility of your app with future versions of the platform.
It is also often of questionable legality.
If you really intend to build a core library -- which is only
appropriate as part of creating a full virtual machine
distribution, as opposed to compiling an application -- then use
the "--core-library" option to suppress this error message.
If you go ahead and use "--core-library" but are in fact
building an application, then be forewarned that your application
will still fail to build or run, at some point. Please be
prepared for angry customers who find, for example, that your
application ceases to function once they upgrade their operating
system. You will be to blame for this problem.
If you are legitimately using some code that happens to be in a
core package, then the easiest safe alternative you have is to
repackage that code. That is, move the classes in question into
your own package namespace. This means that they will never be in
conflict with core system classes. JarJar is a tool that may help
you in this endeavor. If you find that you cannot do this, then
that is an indication that the path you are on will ultimately
lead to pain, suffering, grief, and lamentation.
1 error; aborting
:app:transformClassesWithDexForDebug FAILED
```

Do you have any idea how can I disable checking this in gradle or android studio?

**Comment by ahmadazimi** [comment] 2016-06-05 08:06
Hi there,

I have the same problem using this library in Android Studio with Gradle.
When I try to build my app, gradle stop working on a task and print an error log starts with these lines:
```
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:prePackageMarkerForDebug
:app:transformClassesWithDexForDebug
trouble processing "java/lang/AutoCloseable.class":
```
```
Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.
This is often due to inadvertently including a core library file
in your application's project, when using an IDE (such as
Eclipse). If you are sure you're not intentionally defining a
core class, then this is the most likely explanation of what's
going on.
```
and continue like @ahmadazarnia log.

Is there any way to not use gradle and instead using a compiled jar file? Or this problem may fixed in gradle build system?

**Comment by gitblit** [comment] 2016-06-05 14:28
@ahmadazimi  You are using a compiled jar.  The step that fails is the Android dex step which converts Java bytecode in the jar to Dalvik bytecode to be assembled in your apk.  I have no idea if there is a way to bypass this check in the Android toolchain.

**Comment by ahmadazimi** [comment] 2016-06-06 04:02
Thank you @gitblit 
I'm trying to find a solution for it and If I find it, give it here.

**Comment by ahmadazarnia** [comment] 2016-06-11 11:13
Hi,I tried to get select from MyTable seen below:
`MyTable m = new MyTable();`
`m = db.from(m).where(m._id).is(1).selectFirst();`

but,I get below error while compile:
`com.iciql.IciqlException: unmapped field in statement!
 SELECT  FROM missions WHERE ? = ? `

Please help me!

**Comment by gitblit** [comment] 2016-06-11 13:09
Show me MyTable.

**Comment by ahmadazarnia** [comment] 2016-06-12 04:41
It is MyTable:

`@Iciql.IQTable(name = "MyTable")`
`public class DBMission {`

    @Iciql.IQColumn(primaryKey = true, autoIncrement = true)
    public int _id;
    @Iciql.IQColumn
    public int server_id;
    @Iciql.IQColumn
    public int agent_id;
    @Iciql.IQColumn
    public String mission_name;
    @Iciql.IQColumn
    public String route_name;
    @Iciql.IQColumn
    public String assigned_at;
    @Iciql.IQColumn
    public String import_status;
    @Iciql.IQColumn
    public String description;
    @Iciql.IQColumn
    public boolean is_active;
    @Iciql.IQColumn
    public boolean is_remote_mission;

    public DBMission() {
    }
`}`

**Comment by gitblit** [comment] 2016-06-12 12:30
That looks fine. I've never used this on Android. Perhaps the dex step is discarding file names rendering reflection useless? You could specify a name for the fields in the annotation as a test.

**Comment by gitblit** [comment] 2017-01-31 12:48
Assuming issue has been resolved or OP has moved on.

**Closed by gitblit** 2017-01-31 12:48 UTC
