### ISSUE TITLE
Unable to insert data which all column's value is null

### ISSUE THREAD

**Issue by tspider0176** [gitblit/iciql#22] opened 2016-02-27 09:36 UTC
I make PostgreSQL connection test program by using Iciql. About below entity:

```
@Iciql.IQTable(name="Student") public class Student { 
    @Iciql.IQColumn(name = "ID", primaryKey = true, autoIncrement = true)
     public Integer id; 
    @Iciql.IQColumn(name = "NAME") 
    public String name;
    …
}
```

I try to insert a data which all column has NULL value.

```
db.insert(new Student(null, null));
```

Then below exception occurred: 

```
com.iciql.IciqlException: ERROR: syntax error at or near ")"
  Position: **
INSERT INTO Student() VALUES()
```

Maybe in the insert query construction process which make query in Table(...) and VALUES(...) has some technical problems when insert data which whole column is NULL assigned.

**Comment by gitblit** [comment] 2016-04-04 15:39
This is a duplicate of #19 albeit with a better description.

**Closed** 2016-04-04 17:54 UTC
